require("__pycircuitcompat__.prototypes.compat.active-rails-final-fixes")
require("__pycircuitcompat__.prototypes.compat.alert-scanner-final-fixes")
require("__pycircuitcompat__.prototypes.compat.blueprint-reader-final-fixes")
require("__pycircuitcompat__.prototypes.compat.circuit-hud-v2-final-fixes")
require("__pycircuitcompat__.prototypes.compat.compakt-circuit-final-fixes")
require("__pycircuitcompat__.prototypes.compat.cybersyn-content-reader-final-fixes")
require("__pycircuitcompat__.prototypes.compat.energy-combinator-final-fixes")
require("__pycircuitcompat__.prototypes.compat.fiber-optics-final-fixes")
